# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_food_service', models.BooleanField()),
                ('foodLevel', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HousingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_house_service', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_mental_health_service', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalHealthService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_physical_health_service', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_room_service', models.BooleanField()),
                ('max_room', models.IntegerField()),
                ('filled_rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_support_email', models.CharField(max_length=200)),
                ('shelter_support_tele', models.CharField(max_length=15)),
                ('shelter_address', models.CharField(max_length=200)),
                ('shelter_city', models.CharField(max_length=200)),
                ('shelter_state', models.CharField(max_length=2)),
                ('shelter_desc', models.CharField(max_length=5000)),
                ('service_foods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.FoodService')),
                ('service_house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.HousingService')),
                ('service_mental_illness', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.MentalHealthService')),
                ('service_physical_illness', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.PhysicalHealthService')),
                ('service_rooms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.RoomService')),
            ],
        ),
        migrations.CreateModel(
            name='VeteranAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_veteran_aid', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='shelter',
            name='service_veteran_aid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.VeteranAid'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
