# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 00:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('suffixName', models.CharField(max_length=4)),
                ('birth_date', models.DateField()),
                ('bed_date', models.DateField()),
                ('clientFacility', models.CharField(max_length=20)),
                ('clientRoom', models.IntegerField()),
                ('clientBed', models.IntegerField()),
                ('ssn', models.IntegerField()),
                ('gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female'), ('2', 'Transgender Male to Female'), ('3', 'Transgender Female to Male'), ('97', 'Other'), ('98', "Don't Know"), ('99', 'Refused')], max_length=2)),
                ('age', models.IntegerField()),
                ('phoneNum', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('race', models.CharField(choices=[('0', 'American Indian/Alaskan Native'), ('1', 'Asian'), ('2', 'Black/African American'), ('3', 'Native Hawaiian or Other Pacific Islander'), ('4', 'White/Caucasian'), ('98', "Don't Know"), ('99', 'Refused')], max_length=2)),
                ('condition', models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('98', "Don't Know"), ('99', 'Refused')], max_length=2)),
                ('vetStatus', models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('98', "Don't Know"), ('99', 'Refused')], max_length=2)),
                ('prior', models.CharField(choices=[('0', 'Emergency Shelter'), ('1', 'Transitional Housing for Homeless Persons (including homeless youth)\t'), ('2', 'Permanent Housing for Formerly Homeless Persons (such as SHP, S+C, SRO Mod Rehab)'), ('3', 'Psychiatric Hospital'), ('4', 'Substance Abuse Treatment Center'), ('5', 'Hospital'), ('6', 'Prison'), ('7', 'Rental by Client, No Housing Subsidy'), ('8', 'Rental by Client, with VASH Housing Subsidy'), ('9', 'Rental by Client, with Other (Non-Vash) Housing Subsidy'), ('10', 'Owned by Client, No Housing Subsidy'), ('11', 'Owned by Client, with Housing Subsidy'), ('12', 'Staying or Living in a Family Member\u2019s Room, Apartment, or House'), ('13', 'Staying or Living in a Friend\u2019s Room, Apartment, or House'), ('14', 'Hotel/Motel Paid for Without Emergency Shelter Voucher'), ('15', 'Foster Care Home/Foster Care Group Home'), ('16', 'Places Not Meant for Habitation e.g., (Vehicles, Abandoned Building, Bus/Train/Subway Station/Airport, etc)'), ('17', 'Safe Haven'), ('97', 'Other (Describe)'), ('98', "Don't Know"), ('99', 'Refused')], max_length=2)),
                ('stayLength', models.CharField(choices=[('0', 'One Week or Less'), ('1', 'Less Than a Month'), ('2', '1-3 Months'), ('3', 'More Than 3 Months, but Less Than a Year'), ('4', 'More Than a Year'), ('98', "Don't Know"), ('99', 'Refused')], max_length=2)),
                ('houseStat', models.CharField(choices=[('0', 'Homeless'), ('1', 'Housed, but at-risk of losing housing'), ('2', 'Housed, but at imminent risk of losing housing'), ('3', 'Stably Housed'), ('98', "Don't Know"), ('99', 'Refused')], max_length=2)),
                ('zip', models.IntegerField()),
                ('city2', models.CharField(max_length=60)),
                ('income', models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('98', "Don't Know"), ('99', 'Refused')], max_length=2)),
            ],
        ),
    ]
